version: "3"
services:
    web:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            SERVER: "local"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports:
              - "1433:1433"
        environment:
            SA_PASSWORD: "Morele69"
            ACCEPT_EULA: "Y"